Repository grafana/puppet-promtail, pull requests merged in 2020-01, with the labels that each got.

#13 Add example of merging scrape configs from Hiera
  REFERENCE.md
  manifests/init.pp
Labels: feature

#12 Release file name changed from version v0.4.0
  manifests/install.pp
Labels: bugfix

#14 Bump default promtail version to v1.2.0
  data/common.yaml
Labels: feature

#15 Release prep 0.3.0
  CHANGELOG.md
  REFERENCE.md
  lib/puppet/functions/promtail/strip_yaml_header.rb
  lib/puppet/functions/promtail/to_yaml.rb
  manifests/init.pp
  metadata.json
Labels: maintenance

#16 Updated default checksum on Linux
  data/kernel/Linux.yaml
Labels: bugfix
